# your-repo-name/.github/workflows/first_workflow.yml
name: First Workflow                                               
on: push                                                  
jobs:                         
  build:
    name : Connect to VPS and building
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: rm rf lol